
  CREATE OR REPLACE FORCE VIEW "EMMPAPP"."TP_VIEW_PATIENT_BASE_INFO" ("PATIENTID", "NAME", "GENDER", "AGE", "MARRIAGE", "BIRTHPLACE", "BUSINESS", "ADDRESS", "HOSPITAL", "CATEGORY", "OUTPATIENT", "WARDNO", "INPINFO", "BEDNO", "LASTVISITDATE") AS 
  select 
patient_id as patientId,
name as name,
sex as gender,
extract(year from sysdate) - extract(year from DATE_OF_BIRTH) as age,
'' as marriage,
birth_place as birthPlace,
'' as business,
mailing_address as address,
'' as hospital,
'' as category,
'' as outPatient,
'' as wardNo,
INP_INFO as inpInfo,
'' as bedNo,
last_visit_date as lastVisitDate
from tp_patient_info;



  CREATE TABLE "EMMPAPP"."TP_PATIENT_INFO"
   (	"PATIENT_ID" VARCHAR2(50 BYTE),
	"INP_INFO" VARCHAR2(50 BYTE),
	"NAME" VARCHAR2(50 BYTE),
	"NAME_PONETIC" VARCHAR2(50 BYTE),
	"SEX" VARCHAR2(50 BYTE),
	"DATE_OF_BIRTH" DATE,
	"BIRTH_PLACE" VARCHAR2(50 BYTE),
	"CITYZENSHIP" VARCHAR2(50 BYTE),
	"NATION" VARCHAR2(50 BYTE),
	"ID_INFO" VARCHAR2(50 BYTE),
	"IDENTITY" VARCHAR2(50 BYTE),
	"CHARGE_TYPE" VARCHAR2(50 BYTE),
	"UNIT_IN_CONTRACT" VARCHAR2(5 BYTE),
	"MAILING_ADDRESS" VARCHAR2(50 BYTE),
	"ZIP_CODE" VARCHAR2(50 BYTE),
	"PHONE_NUMBER_HOME" VARCHAR2(50 BYTE),
	"PHONE_NUMBER_BUSINESS" VARCHAR2(50 BYTE),
	"NEXT_OF_KIN" VARCHAR2(50 BYTE),
	"RELATIONSHIP" VARCHAR2(50 BYTE),
	"NEXT_OF_KIN_ADDR" VARCHAR2(100 BYTE),
	"NEXT_OF_KIN_ZIP_CODE" VARCHAR2(50 BYTE),
	"NEXT_OF_KIN_PHONE" VARCHAR2(50 BYTE),
	"LAST_VISIT_DATE" DATE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "EMMPAPP" ;
